# Generated by Django 5.2.2 on 2026-03-16 11:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('language', models.CharField(choices=[('EN', 'Inglés'), ('ES', 'Español'), ('FR', 'Francés'), ('DE', 'Alemán'), ('IT', 'Italiano'), ('PT', 'Portugués'), ('JA', 'Japanese'), ('ZH', 'Chinese')], max_length=2)),
                ('audio_file', models.FileField(upload_to='media/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'ogg', 'm4a'])], verbose_name='Archivo de audio')),
                ('lrc_file', models.FileField(upload_to='media/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['lrc', 'txt'])], verbose_name='Archivo LRC con letra sincronizada')),
                ('background_image', models.FileField(upload_to='media/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png'])], verbose_name='Imagen de fondo')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se creó el registro', verbose_name='Fecha de creación')),
                ('category', models.CharField(choices=[('POP', 'Pop'), ('ROCK', 'Rock'), ('JAZZ', 'Jazz'), ('HIPHOP', 'Hip-Hop'), ('CLASSICAL', 'Classical'), ('REGGAE', 'Reggae'), ('LATIN', 'Latin'), ('KPOP', 'K-Pop'), ('COUNTRY', 'Country'), ('BLUES', 'Blues'), ('FOLK', 'Folk'), ('ELECTRONIC', 'Electronic'), ('R&B', 'R&B'), ('SOUL', 'Soul'), ('METAL', 'Metal'), ('PUNK', 'Punk'), ('ALTERNATIVE', 'Alternative'), ('INDIE', 'Indie'), ('GOSPEL', 'Gospel'), ('WORLD', 'World Music')], max_length=20)),
                ('number_times_played', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Veces reproducida')),
            ],
            options={
                'verbose_name': 'Canción',
                'verbose_name_plural': 'Canciones',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['title', 'artist'], name='song_models_title_b7f0de_idx'), models.Index(fields=['category'], name='song_models_categor_25935e_idx')],
            },
        ),
        migrations.CreateModel(
            name='SongUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played_at', models.DateTimeField(auto_now=True)),
                ('correct_guesses', models.IntegerField(default=0, verbose_name='Número de aciertos')),
                ('wrong_guesses', models.IntegerField(default=0, verbose_name='Número de errores')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='song_models.song', verbose_name='Canción asociada')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario asociado')),
            ],
            options={
                'verbose_name': 'Estadística de canción por usuario',
                'verbose_name_plural': 'Estadísticas de canciones por usuario',
                'ordering': ['-played_at'],
                'unique_together': {('user', 'song')},
            },
        ),
    ]
