# Generated by Django 5.2.2 on 2026-04-21 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song_models', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='songuser',
            unique_together=set(),
        ),
    ]
